### ISSUE TITLE
Possible values for runservices.run.cnrm.cloud.google.com ingress field

### ISSUE THREAD

**Issue by neuromantik33** [GoogleCloudPlatform/k8s-config-connector#609]
Hello, I'm having trouble creating a RunService (Cloud run service) with an internal traffic type. I've tried `internal`, `INTERNAL` and `INGRESS_TRAFFIC_INTERNAL` to no avail and there is no documentation on the field.

Can anyone please tell me what are the possible values? There should only be 3

Thanks in advance

**Comment by diviner524** [comment]
Hi @neuromantik33 , thank you for reporting this user friction.

To clarify, are you referring to the `traffic[].type` in [RunService spec](https://cloud.google.com/config-connector/docs/reference/resource-docs/run/runservice#spec)?

**Comment by tommycouri-bestbuy** [comment]
Hello, 

I am having similar issues here. When setting the following ingress policies, it appears that it continues to default to INGRESS_TRAFFIC_ALL when deploying the instance. I understand that this resource is still in Alpha, but I wanted to bring this to your attention. 

Ingress settings:
INGRESS_TRAFFIC_ALL, INGRESS_TRAFFIC_INTERNAL_ONLY, INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER

**Comment by petelah** [comment]
> I am having similar issues here. When setting the following ingress policies, it appears that it continues to default to INGRESS_TRAFFIC_ALL when deploying the instance. I understand that this resource is still in Alpha, but I wanted to bring this to your attention.

Experiencing the same issue. It is fine when deploying via cli and specifying `--ingress=internal-and-cloud-load-balancing` but not ideal for our setup to not have it defined with IAC.

**Comment by rafaeltello** [comment]
Hello @neuromantik33, @tommycouri-bestbuy and @petelah ! Thanks for your report! We have discovered an issue with the way we handle this flag in Cloud Run when coming from config connector. A fix has been submitted now. Due to our internal rollout speed, we expect this issue to be fully resolved by April 8th afternoon PDT.

Apologies for any inconvenience, and thanks again for helping us test this Alpha release!
-Rafael, from Cloud Run team

**Comment by petelah** [comment]
Great news @rafaeltello !
Thanks for the response.

**Comment by petelah** [comment]
Hey guys,

Just checking if this is resolved?

I am still having trouble via config connector not accepting:
`ingress: "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"`
After deployment it defaults to authenticated traffic and allow all.

Thanks,

Peter.

**Comment by diviner524** [comment]
@petelah 

Could you please provide:

* Kubernetes Cluster Version
* Config Connector Version
* The YAML you used to create the KCC resource
* Reproduce steps

@rafaeltello mentioned the previous issue is fixed, and this might be a different one. We will try to reproduce it first.

Also if this is time sensitive, we suggest you to create a GCP support case to track the issue as well.

**Comment by tommycouri-bestbuy** [comment]
Hi @diviner524 - I'm still having issues with this as well. 

Kubernetes Cluster Version: v1.21.0
Config Connector Version: 1.70.0
YAML file:
`  apiVersion: run.cnrm.cloud.google.com/v1beta1
  kind: RunService
  metadata:
    name: runservice-sample-internal
  spec:
    ingress: "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
    launchStage: "GA"
    location: "us-central1"
    projectRef:
      # Replace ${PROJECT_ID?} with your project ID.
      external: projects/bbyus-cplat-discovery-rn-s10
    template:
      containers:
        - env:
            - name: "FOO"
              value: "bar"
          image: "us-docker.pkg.dev/cloudrun/container/hello"
      scaling:
        maxInstanceCount: 3
    traffic:
      - percent: 100
        type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"`

When I deploy this with INGRESS_TRAFFIC_INTERNAL_ONLY or INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER this is still defaulting to INGRESS_TRAFFIC_ALL on deployment.

**Comment by rafaeltello** [comment]
Thanks @tommycouri-bestbuy. I was able to reproduce the issue, and found a different root cause. The issue is now fixed internally, and we have added a test very similar to your yaml file to ensure we don't regress again. Due to our rollout timelines, I am hoping this is fully rolled out by the end of next week (Friday May 20th).

Apologies again for the inconvenience, and thanks again for helping us test this Alpha release!
-Rafael, from Cloud Run team

**Comment by tommycouri-bestbuy** [comment]
Thanks @rafaeltello - this is working for me now.

**Comment by ldanielmadariaga** [comment]
This item has been open for >12 months. As part of scheduled repository maintenance, this Issue/PR will be closed. If this is still a critical ask, please re-open and work with your Google Cloud Account team to prioritize it with GCP KCC Product Management.
